# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.3.0
mod_root = com.limachi.lim_lib
mod_id = lim_lib
enabled_platforms = fabric,neoforge
readable_name = LIMachi's Library
description = description
author = LIMachi
license = TBD

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
architectury_api_version = 13.0.8
fabric_loader_version = 0.16.10
fabric_api_version = 0.115.4+1.21.1
neoforge_version = 21.1.84
