modLoader="javafml" #mandatory
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
    modId="lim_lib"
    version="${file.jarVersion}"
    displayName="LIMachi's Library"
    authors="LIMachi"
    description=''''''

[[dependencies.lim_lib]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lim_lib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lim_lib]]
    modId="curios"
    mandatory=false
    versionRange="[1.19.2-5.1.1.0,)"
    ordering="AFTER"
    side="BOTH"