modLoader="javafml" #mandatory
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
    modId="lim_lib"
    version="${file.jarVersion}"
    displayName="LIMachi's Library"
    updateJSONURL="https://raw.githubusercontent.com/LIMachi/lim_lib/master/forge_changelog.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/limlib"
    #logoFile="lim_lib.png"
    #credits=""
    authors="LIMachi"
    description=''''''

[[dependencies.lim_lib]]
    modId="forge"
    mandatory=true
    versionRange="[47.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lim_lib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
